import './globals.css'
import type { Metadata } from 'next'
import { Comfortaa } from 'next/font/google'
import theme from '../theme/theme'
import ThemeProvider from '../libraries/themeProvider'

const comfortaa = Comfortaa({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
    <html lang="en">
      <ThemeProvider theme={theme}>
      <body >{children}</body>
      </ThemeProvider>
    </html>
    </>
  )
}
